# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Geocodeur
                                 A QGIS plugin
 CSV to points georeferenced
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-06
        copyright            : (C) 2024 by Vittorio
        email                : vittorio.toffolutti@ensg.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Geocodeur class from file Geocodeur.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pyqgis_script import Geocodeur
    return Geocodeur(iface)
